# Generated by Django 4.1.7 on 2023-03-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicada',
            new_name='exibir',
        ),
    ]
